# Base configs
# baseurl: "https://jayyf9.github.io/photography/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Jake French"
subtitle: "See the world through my eyes!"
author: "Jake French"
header:
 title: "Photography"
 subtitle: "by Jake French"
footer:
 name: "Hey there, my name is Jake"
 bio: "I am a photographer based in the Netherlands. Check out some of my work and feel free to get in touch."
 github: ""
web_design: "JF"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://x.com/Jayyf9"
  instagram: "https://www.instagram.com/jayyf9/"
  linkedin: "https://www.linkedin.com/in/jake-french-200a0462/"
  github: "https://github.com/jayyf9"
